---
abstract: 'Another CSS minifier'
author:
  - 'Lee Johnson <leejo@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CSS-Packer
no_index:
  directory:
    - t
    - inc
requires:
  Regexp::RegGrp: 1.001_001
resources:
  bugtracker: https://github.com/leejo/css-packer-perl/issues
  homepage: https://metacpan.org/module/CSS::Packer
  license: http://dev.perl.org/licenses/
  repository: https://github.com/leejo/css-packer-perl
version: '2.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
